In [13]:
import numpy as np

In [14]:
A = np.array([[2,6,5,2],
             [2,-2,2,3],
             [1,5,4,0]])

B = np.array([[2,9,0,3,0],
             [3,6,4,-2,2],
             [1,3,5,0,1],
             [3,0,2,0,5]])

print(A.shape)
print(B.shape)

(3, 4)
(4, 5)


In [15]:
print(np.matmul(A,B))  # Matrix Multiplication

[[33 69 53 -6 27]
 [ 9 12  8 10 13]
 [21 51 40 -7 14]]


#### Einsum is powerful function that combines multiple functions of numpy

In [20]:
 print(np.einsum("ij, jk -> ki", A, B))   # Matrix Multiplication followed by transpose

[[33  9 21]
 [69 12 51]
 [53  8 40]
 [-6 10 -7]
 [27 13 14]]


In [21]:
print(np.einsum("ij, jk -> ik", A, B)) # Matrix Multiplication

[[33 69 53 -6 27]
 [ 9 12  8 10 13]
 [21 51 40 -7 14]]


In [22]:
B_new = np.array([[2,9,0,3],
             [3,6,4,-2],
             [1,3,5,0]])

print(np.einsum("ij, ij -> ij", A, B_new)) # Simple Multiplication

[[  4  54   0   6]
 [  6 -12   8  -6]
 [  1  15  20   0]]


In [23]:
print(np.einsum("ij->ji",A)) # Transpose

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


### Three dimensional matrix multiplication

In [25]:
A3 = np.array([[[2,6,5,2],
                [2,-2,2,3],
                [1,5,4,0]],
              [[1,3,1,22],
               [0,2,2,0],
               [1,5,4,1]] ])

B3 = np.array([[[1,9,0,3,0],
                [3,6,8,-2,2],
                [1,3,5,0,1],
                [3,0,2,0,5]],
              [[1,0,0,3,0],
               [3,0,4,-2,2],
               [1,0,2,0,0],
               [3,0,1,1,0]] ])
print(A3.shape,B3.shape)

(2, 3, 4) (2, 4, 5)


In [26]:
print(np.matmul(A3,B3))

[[[31 69 77 -6 27]
  [ 7 12  0 10 13]
  [20 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [29]:
print(np.einsum("bij,bjk -> bik",A3,B3))

[[[31 69 77 -6 27]
  [ 7 12  0 10 13]
  [20 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [30]:
 print(np.sum(A3))

72


In [32]:
print(np.einsum("bij -> ",A3)) # Summing up all elements

72


In [36]:
Q = np.random.randn(32,64,512)
K = np.random.randn(32,128,512)

In [37]:
np.einsum("bqm,bkm -> bqk",Q,K).shape

(32, 64, 128)