In [1]:
import tensorflow as tf
from tensorflow import keras

# Tensors

## Zero, One, Two and Three Dimensional

In [2]:
zerod = tf.constant(4)

In [3]:
print("Zero Dimensional Tensor\n",zerod)

Zero Dimensional Tensor
 tf.Tensor(4, shape=(), dtype=int32)


In [4]:
oned = tf.constant([1,2,3])

In [5]:
print("One Dimensional Tensor\n",oned)

One Dimensional Tensor
 tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
twod = tf.constant([[1,2,3],[4,5,6]])

In [7]:
print("Two Dimensional Tensor\n",twod)

Two Dimensional Tensor
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
threed = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,5]],[[7,9,6],[4,2,8]]])

In [9]:
print("Three Dimensional Tensor\n",threed)

Three Dimensional Tensor
 tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 5]]

 [[7 9 6]
  [4 2 8]]], shape=(3, 2, 3), dtype=int32)


## Changing Datatypes

In [10]:
oned2 = tf.constant([1,2,3],dtype=tf.float32)

print(oned2)

# Casting

In [11]:
oned2 = tf.cast(oned2,tf.int32)

In [12]:
print(oned2)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


## Array to Tensors

In [13]:
import numpy as np

In [14]:
arr = np.array([1,2,3])

In [15]:
converted_tensor = tf.convert_to_tensor(arr)

In [16]:
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


# Identity Tensor

In [17]:
eye_tensor = tf.eye(num_rows=3,num_columns=None,batch_shape=None,dtype=tf.dtypes.float32,name=None)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [18]:
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [19]:
eye_tensor2 = tf.eye(num_rows=5,num_columns=3,batch_shape=None,dtype=tf.dtypes.float32,name=None)

In [20]:
print(eye_tensor2)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [21]:
eye_tensor3 = tf.eye(num_rows=3,num_columns=3,batch_shape=[2,2],dtype=tf.dtypes.float32,name=None)

In [22]:
print(eye_tensor3)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 2, 3, 3), dtype=float32)


# Scalar Tensor

#### These tensors initialise all elements with the provided scalar values

In [23]:
scalar_tensor = tf.fill([2,3,4],5,name=None)

In [24]:
print(scalar_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [25]:
one_tensor = tf.ones([2,3,4],dtype=tf.float32,name=None)

In [26]:
print(one_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [27]:
one_like_tensor = tf.ones_like(scalar_tensor,dtype=tf.float32)

In [28]:
print(one_like_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


#### tf.zeros works similarly

## Tensor Properties

In [29]:
print(threed.ndim)

3


In [30]:
print(threed.shape)

(3, 2, 3)


#### Apart from shape tf.shape return a tensor

In [31]:
print(tf.shape(threed))

tf.Tensor([3 2 3], shape=(3,), dtype=int32)


In [32]:
print(tf.rank(threed))

tf.Tensor(3, shape=(), dtype=int32)


In [33]:
print(tf.size(threed))

tf.Tensor(18, shape=(), dtype=int32)


## Random Tensors

In [34]:
random_tensor = tf.random.normal([3,2],
                                mean = 0.0,
                                stddev=1.0,
                                dtype=tf.dtypes.float32,
                                seed=None,
                                name=None
                                )


In [35]:
print(random_tensor)

tf.Tensor(
[[-0.7531915   0.33029288]
 [-1.4756422   0.67659163]
 [-0.43318895 -0.9066143 ]], shape=(3, 2), dtype=float32)


In [36]:
random_uniform_tensor = tf.random.uniform(
[5,],
minval=0,
maxval=8,
dtype=tf.dtypes.float32,
seed=None,
name=None
)

In [37]:
print(random_uniform_tensor)

tf.Tensor([3.3975296  0.44068336 7.9190636  0.2734232  5.7355604 ], shape=(5,), dtype=float32)


In [38]:
random_uniform_tensor2 = tf.random.uniform(
[5,],
minval=0,
maxval=8,
dtype=tf.dtypes.int32,
seed=None,
name=None
)

In [39]:
print(random_uniform_tensor2)

tf.Tensor([5 3 1 7 0], shape=(5,), dtype=int32)


##### Seed value is to generate reproducible random tensors

In [40]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [41]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [42]:
tf.random.set_seed(8)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 0 4], shape=(3,), dtype=int32)
tf.Tensor([0 4 3], shape=(3,), dtype=int32)


In [43]:
tf.random.set_seed(8)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 0 4], shape=(3,), dtype=int32)
tf.Tensor([0 4 3], shape=(3,), dtype=int32)


# Indexing Tensors

In [44]:
indexed_tensor = tf.constant([3,6,2,4,6,66,7])
print(indexed_tensor)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [45]:
print(indexed_tensor[0:4])
print(indexed_tensor[1:6:2])

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)


In [46]:
print(tf.range(2,10))

tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)


In [47]:
print(twod)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [48]:
print(twod[:,0:2])

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [49]:
 print(threed)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 5]]

 [[7 9 6]
  [4 2 8]]], shape=(3, 2, 3), dtype=int32)


In [50]:
print(threed[0,:,:])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [51]:
print(threed[0:2,:,0:2])

tf.Tensor(
[[[1 2]
  [4 5]]

 [[7 8]
  [0 1]]], shape=(2, 2, 2), dtype=int32)


# Mathematical Operations

In [52]:
x = tf.constant([-2,-5,-0.3,1,2,0.5])
print(tf.abs(x))

tf.Tensor([2.  5.  0.3 1.  2.  0.5], shape=(6,), dtype=float32)


In [53]:
x = tf.constant(-2.25+4.75j)
print(tf.abs(x))
print(tf.sqrt(((-2.25)**2)+((4.75)**2)))

tf.Tensor(5.25594901040716, shape=(), dtype=float64)
tf.Tensor(5.255949, shape=(), dtype=float32)


In [54]:
x1 = tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x2 = tf.constant([7,6,2,6,7,11],dtype=tf.int32)

print("Addition\n",tf.add(x1,x2))
print("Multiplication\n",tf.multiply(x1,x2))
print("Subtraction\n",tf.subtract(x1,x2))
print("Division\n",tf.divide(x1,x2))

Addition
 tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
Multiplication
 tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
Subtraction
 tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)
Division
 tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [55]:
x1 = tf.constant([5,3,6,6,4,6],dtype=tf.float32)
x2 = tf.constant([7,6,2,6,0,11],dtype=tf.float32)
print(tf.divide(x1,x2))
print(tf.math.divide_no_nan(x1,x2))

tf.Tensor([0.71428573 0.5        3.         1.                inf 0.54545456], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.         0.54545456], shape=(6,), dtype=float32)


In [56]:
x1 = tf.constant([5,3,6,6,4,6],dtype=tf.float32)
x2 = tf.constant([[7],[5],[3]],dtype=tf.float32)
print(x1.shape)
print(x2.shape)
print(tf.multiply(x1,x2))

(6,)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


## tf.math.argmax
#### It accepts a tensor and returns the index of largest element

In [57]:
x_argmax = tf.constant([20,10,30,13,100,8,100,50])
print(tf.math.argmax(x_argmax))

tf.Tensor(4, shape=(), dtype=int64)


#### For multidimensional tensors we can provide axis, 0 mean column wise comparison and 1 means row wise

In [58]:
x_argmax = (
    [[2,20,30,3,6],
     [3,11,16,1,8],
     [14,45,23,5,27]]
)
print(tf.math.argmax(x_argmax,0))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [59]:
print(tf.math.argmax(x_argmax,1))

tf.Tensor([2 2 1], shape=(3,), dtype=int64)


#### This works similar for argmin

In [60]:
print(tf.math.argmin(x_argmax),0)

tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64) 0


In [61]:
print(tf.math.argmin(x_argmax),0)

tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64) 0


## tf.math.pow
#### raises power of each element of first tensor to elements of second element

In [62]:
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[3,0],[1,4]])
print(tf.pow(x,y))

tf.Tensor(
[[ 8  1]
 [ 3 81]], shape=(2, 2), dtype=int32)


## Reduce functions
#### reduce functions calculates on all elements as a single array

In [63]:
print(twod)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [64]:
print(tf.math.reduce_sum(twod,axis=None,keepdims=False,name=None))

tf.Tensor(21, shape=(), dtype=int32)


In [65]:
print(tf.math.reduce_sum(twod,axis=None,keepdims=True,name=None))

tf.Tensor([[21]], shape=(1, 1), dtype=int32)


In [66]:
print(tf.math.reduce_max(twod,axis=None,keepdims=False,name=None))

tf.Tensor(6, shape=(), dtype=int32)


In [67]:
print(tf.math.reduce_sum(twod,axis=0,keepdims=False,name=None))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [68]:
print(tf.math.reduce_sum(twod,axis=1,keepdims=False,name=None))

tf.Tensor([ 6 15], shape=(2,), dtype=int32)


In [69]:
twod = tf.constant([[1, 2, 3],
 [4, 5, 6]],dtype=tf.float32)

In [70]:
print(tf.math.reduce_mean(twod,axis=None,keepdims=False,name=None))

tf.Tensor(3.5, shape=(), dtype=float32)


In [71]:
print(tf.math.reduce_std(twod,axis=None,keepdims=False,name=None))

tf.Tensor(1.7078251, shape=(), dtype=float32)


In [72]:
tf.math.top_k(twod,k=2)

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 2.],
       [6., 5.]], dtype=float32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1]])>)

# Algebraic Operations 

## tf.linalg.matmul

In [73]:
x1 = tf.constant([[1,2,0],[3,5,-1]])
x2 = tf.constant([[1,2,0],[3,5,-1],[4,5,6]])
tensor_matmul=tf.linalg.matmul(x1,x2,
                 transpose_a=False,
                 transpose_b=False,
                 adjoint_a=False,
                 adjoint_b=False,
                 a_is_sparse=False,
                 b_is_sparse=False,
                 output_type=None,
                 name=None)
print(tensor_matmul)

tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)


In [74]:
print(x1@x2)

tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)


## Transpose

In [75]:
tf.transpose(x1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]])>

In [76]:
print(x1)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


#### While doing matrix multiplication in three dimensional tensors, dimension of all two dimensional tensors inside should match the multiplication criteria

## Bandpart

In [77]:
tensor_two_d = tf.constant([[1,-2,0],
                           [3,5,100],
                           [1,5,6],
                           [2,3,1]])

# (m-n<=Lower)&(n-m<=upper) 
# m=rows n=columns

print(tf.linalg.band_part(tensor_two_d,0,0))


tf.Tensor(
[[1 0 0]
 [0 5 0]
 [0 0 6]
 [0 0 0]], shape=(4, 3), dtype=int32)


In [78]:
print(tf.linalg.band_part(tensor_two_d,0,-1))

tf.Tensor(
[[  1  -2   0]
 [  0   5 100]
 [  0   0   6]
 [  0   0   0]], shape=(4, 3), dtype=int32)


In [79]:
print(tf.linalg.band_part(tensor_two_d,-1,0))

tf.Tensor(
[[1 0 0]
 [3 5 0]
 [1 5 6]
 [2 3 1]], shape=(4, 3), dtype=int32)


#### If the condition (m-n<=Lower)&(n-m<=Upper) return true then the value at that specific position is retained else it becomes zero. Lower and Upper are passed as arguments. 
#### For 0 and 0 it returns a digonal matrix.
#### For 0 and -1 it returns a upper triangular matrix
#### For -1 and 0 it returns a lower triagular matrix

## Inverse

In [80]:
tensor_two_d = tf.constant([[1,-2,0],
                           [3,5,100],
                           [1,5,6]],dtype= tf.float32)

two_d_inv = tf.linalg.inv(tensor_two_d)
print(two_d_inv)

tf.Tensor(
[[ 0.74132484 -0.01892744  0.3154574 ]
 [-0.12933758 -0.00946372  0.1577287 ]
 [-0.01577287  0.01104101 -0.01735016]], shape=(3, 3), dtype=float32)


#### When we multiply a matrix with its inverse we get a identity matrix

In [81]:
print(tensor_two_d@two_d_inv)

tf.Tensor(
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0986328e-03  9.9990845e-01 -6.1035156e-05]
 [-4.2724609e-04  1.5258789e-05  9.9990845e-01]], shape=(3, 3), dtype=float32)


In [82]:
s,v,d = tf.linalg.svd(tensor_two_d)
print(s)
print(v)
print(d)

tf.Tensor([100.366325    5.105901    1.2371689], shape=(3,), dtype=float32)
tf.Tensor(
[[ 7.4973481e-04  3.7569967e-01  9.2674106e-01]
 [-9.9803799e-01  5.8300667e-02 -2.2827385e-02]
 [-6.2605947e-02 -9.2490584e-01  3.7500623e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.03044816 -0.07330807  0.9968445 ]
 [-0.05285358 -0.9957936  -0.07484518]
 [-0.9981381   0.05496549 -0.02644551]], shape=(3, 3), dtype=float32)


# Common Tensorflow Functions

## Expand Dimensions

In [83]:
print(threed)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 5]]

 [[7 9 6]
  [4 2 8]]], shape=(3, 2, 3), dtype=int32)


In [84]:
print(threed.shape)

(3, 2, 3)


In [85]:
print(tf.expand_dims(threed,axis=0).shape)

(1, 3, 2, 3)


In [86]:
print(tf.expand_dims(threed,axis=1).shape)

(3, 1, 2, 3)


In [87]:
print(tf.expand_dims(threed,axis=2).shape)

(3, 2, 1, 3)


In [88]:
print(tf.expand_dims(threed,axis=3).shape)

(3, 2, 3, 1)


## Squeeze Dimensions

In [89]:
expanded3=tf.expand_dims(threed,axis=3)
print(tf.squeeze(expanded3,axis=3).shape)

(3, 2, 3)


In [90]:
expanded2=tf.expand_dims(threed,axis=2)
print(tf.squeeze(expanded3,axis=3).shape)

(3, 2, 3)


## Reshape

In [91]:
x_reshape = tf.constant([[3,5,6,6,],
                         [4,6,1,2]])

tf.reshape(x_reshape,[8])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 5, 6, 6, 4, 6, 1, 2])>

In [92]:
tf.reshape(x_reshape,[4,2])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 6],
       [4, 6],
       [1, 2]])>

In [93]:
tf.reshape(x_reshape,[4,2,1])

<tf.Tensor: shape=(4, 2, 1), dtype=int32, numpy=
array([[[3],
        [5]],

       [[6],
        [6]],

       [[4],
        [6]],

       [[1],
        [2]]])>

## Concat

In [94]:
t1 = tf.constant([[1,2,3],
                  [4,5,6]])
t2 = tf.constant([[7,8,9],
                  [10,11,12]])

tf.concat([t1,t2],0)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [95]:
t1 = [[1,2,3],
      [4,5,6]]
t2 = [[7,8,9],
     [10,11,12]]

tf.concat([t1,t2],0)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [96]:
tf.concat([t1,t2],1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])>

## Stacking

In [97]:

tf.stack([t1,t2],0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [98]:
tf.stack([t1,t2],1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])>

## Pad

In [102]:
t1 = tf.constant([[1,2,3],
                [4,5,6]])
t2 = tf.constant([[1,2],
                 [3,4]])


tf.pad(t1,t2,"CONSTANT",constant_values=0)

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

## Gather

In [103]:
params = tf.constant(['p0','p1','p2','p3','p4','p5'])

In [104]:
tf.gather(params,[1,2,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [105]:
tf.gather(params,tf.range(1,4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [106]:
params = tf.constant([[0,1.0,2.0],
                      [10.0,11.0,12.0],
                      [20.0,21.0,22.0],
                      [30.0,31.0,32.0]])

In [107]:
tf.gather(params,[3,1])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[30., 31., 32.],
       [10., 11., 12.]], dtype=float32)>

In [109]:
tf.gather(params,[2,1],axis=1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 2.,  1.],
       [12., 11.],
       [22., 21.],
       [32., 31.]], dtype=float32)>

In [111]:
indices = [[0]]
params = [['a','b'],
          ['c','d']]
tf.gather_nd(params,indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'a', b'b']], dtype=object)>

In [112]:
indices = [[0],
           [1]]
params = [['a','b'],
          ['c','d']]
tf.gather_nd(params,indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [113]:
indices = [1,1]
params = [['a','b'],
          ['c','d']]
tf.gather_nd(params,indices)

<tf.Tensor: shape=(), dtype=string, numpy=b'd'>

# Ragged Tensors

#### A ragged tensor is simply a non rectangular tensor which has different number of columns in each row

In [114]:
tensor_ragged = tf.ragged.constant([[1,2,0],
                                    [3],
                                    [1,5,6,5,6],
                                    [2,3]])
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [115]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3,1,4,1,5,9,2,6],
    row_lengths=[4,0,3,1,0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


# Sparse Tensors

#### Sparse tensors are simply tensors which has mostly zero as its elements

In [116]:
tensor_sparse = tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]],
    values=[11,56],
    dense_shape=[5,6])

In [117]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [118]:
print(tf.sparse.to_dense(tensor_sparse))

tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 56  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)


# String Tensors

In [119]:
tensor_string =  tf.constant(["hello","I","am","a","string"])

In [120]:
print(tensor_string)

tf.Tensor([b'hello' b'I' b'am' b'a' b'string'], shape=(5,), dtype=string)


In [124]:
print(tf.strings.join(tensor_string,separator=" "))

tf.Tensor(b'hello I am a string', shape=(), dtype=string)


# Variables

In [125]:
x = tf.constant([1,2])

In [127]:
x_var =  tf.Variable(x,name="var1")
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


In [128]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2])>

In [130]:
with tf.device('GPU:0'):
    x_var =  tf.Variable(0.2)
    
print(x_var.device)

/job:localhost/replica:0/task:0/device:GPU:0


<function device_v2 at 0x0000028B66558310>
